 const products =[{
    "name":"K60 RGB Pro SE",
    "price":79.99,
    "description":"",
    "specifications":[{
                    "model":"CH-910D119-NA",
                    "KeyboardInterface":"USB 3.0",
                    "DesignStyle":"Gaming",
                    "Palm Rest":"Full length, detachable magnetic cushioned with memory foam cushion",
                    "Mechanical Keyboard":"Yes",
                    "Key Switch Type":"Cherry Viola",
                    "KeyboardColor":"Black",
                    "Dimensions":"1.46 x 17.40 x 5.40",
                    "Backlit":"Yes",
                    "Type":"Wired"}],
    "img": "https://www.newegg.com/shadow-black-lenovo-ideapad-gaming-3-15ihu6-82k1015dus/p/N82E16834646427",
    "stock":1,
    "onDiscount":false,
    "discountPercentage":0,
    "freeShipping":false,
},{
    "name":"SK622 Wireless",
    "price":109.99,
    "description":"Low Profile Switches: A reduced travel distance and actuation point with the same signature durability and precision.Portable 60% Layout: Compact layout and design, perfect for on-the-go use with mobile devices and laptops. Hybrid Wireless: Choose between wired Type-C connectivity or Bluetooth 4.0 wireless for up to 3 devices.Ergonomic Upgrades: New ergonomic keycaps and adjustable feet allow you the comfortable typing experience you want, your way.Multiple OS Support: Use with MacOS, iOS, Android, and Windows 8 and above - and easily soft-switch between all devices with a simple keypress.RGB Backlighting: Keep the lightshow going with per-key backlighting and surrounding LED ring with endless customization.",
    "specifications":[{
                      "model":"SK-622-GKTR1-US",
                      "Keyboard Interface":"USB Type-C (Keyboard Side), USB 2.0 Type A (Computer Side)",
                      "Design Style":"TKL",
                      "Palm Rest":"No",
                      "Mechanical Keyboard":"Yes",
                      "Key Switch Type":"Red Switch",
                      "Keyboard Color":"Gunmetal",
                      "Backlit":"RGB",
                      "Dimensions":`Standard: (1.19" x 11.54" x 4.06"
                       Feet Open: 1.69" x 11.54" x 4.06")`,
                      "Type":"Wired / Bluetooth 4.0",
                      "Power Supply":"4000 mAh (2 x 2000 mAh)",
                      "Operating System Supported":"",
                      }],
                   
    "img":"https://www.newegg.com/cooler-master-sk622-red-mechanical-black/p/N82E16823129112",
    "stock":1,
    "onDiscount":false,
    "discountPercentage":0,
    "freeShipping":false,

}
// ,{
//     "name":"Z12 RGB",
//     "price":14.99,
//     "description":"Dedicated and programmable macro keys, plus a full set of media keys give you full control at your fingertips.IP32 Spill-Resistant es capaz de soportar derrames accidentales.",
//     "specifications":[{
//                       "model":"834-W0-12US-KR",
//                       "Keyboard Interface":"USB 2.0",
//                       "Key Switch Type":"Membrane",
//                       "Keyboard Color":"Black",
//                       "Dimensions":`(19.57" x 7.80" x 2.05")`,
//                       "Type":"Wired"}],
//     "img":"https://www.newegg.com/evga-z12-rgb-gaming-keyboard-membrane-black/p/N82E16823953009",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":true,
// },{
//     "name":"Vigor GK50 Elite",
//     "price":59.99,
//     "description":"Mechanical switches provide accuracy and endurance.The ergonomic high-low keycap design reduces strain and pain of hands and wristsBrushed metal top plate and octagonal-shaped keycaps.Stunning per-key RGB lighting and various effects.Steady Gaming Base provides incredible feedback and anti-slip performance.Fine-tune detail settings with Dragon Center.",
//     "specifications":[{
//                       "model":"?S11-04US256-CLA",
//                       "Keyboard Interface":"USB 2.0",
//                       "Design Style":"Gaming",
//                       "Palm Rest":"No",
//                       "Mechanical Keyboard":"Yes",
//                       "Key Switch Type":"Kailh Blue",
//                       "Backlit":"Per-key RGB Mystic Light",
//                       "Dimensions":`(1.50" x 17.13" x 5.31")`,
//                       "Type":"Wired"}],
//     "img":"https://www.newegg.com/msi-vigor-gk50-elite-kailh-blue/p/N82E16823167039",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },{
//     "name":"K55 RGB PRO XT",
//     "price":69.99,
//     "description":"Dynamic Per-Key RGB Backlighting: Light up your desktop with ten onboard lighting effects or customize your own vibrant lighting effects with CORSAIR iCUE software.Six Dedicated Macro Keys: Activate functions, shortcuts, or keypresses in just one stroke with six dedicated macro keys, easily set up through CORSAIR iCUE software, or use instant streaming commands through Elgato Stream Deck software.Dust and Spill-Resistant Design: IP42-rated protection guards against accidents so your gameplay never has to stop.",
//     "specifications":[{
//                       "model":"CH-9226715-NA",
//                       "Keyboard Interface":"USB 3.0 Type-A",
//                       "Design Style":"Gaming",
//                       "Palm Rest":"Detachable",
//                       "Keyboard Color":"Black",
//                       "Backlit":" 	RGB, 16.8 million colors",
//                       "Dimensions":`(1.42" x 19.00" x 6.58")`,
//                       "Type":"Wired"}],
                      
//     "img":"https://www.newegg.com/p/N82E16823816144",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },{
//     "name":"Devastator 3",
//     "price":41.88,
//    "description":"Ergonomic styling from top to bottom.Custom membrane design.Seven colors for customized personality.A precision mouse to elevate your game.unctional and durable",
//     "specifications":[{
//                     "model":"SGB-3000-KKMF1-US",
//                     "Keyboard Interface":"USB 1.1",
//                     "Design Style":"Gaming",
//                     "Palm Rest":"Yes",
//                     "Key Switch Type ":"Membrane",
//                     "Keyboard Color":"Black",
//                     "Dimensions":`Keyboard: (1.40" x 17.70" x 5.84"
//                     Mouse: 1.44" x 2.54" x 4.69")`,
//                     "Backlit":"7-Color RGB",
//                     "Type ":"Wired"}],
                    
//     "img":"https://www.newegg.com/black-cooler-master-devastator-3-membrane/p/N82E16823129082",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },{
//     "name":"G502",
//     "price":98.00,
//     "description":"LIGHTSPEED WirelessG502 is an icon, topping the charts through every generation, and the mouse of choice for serious gamers. Now, G502 joins the ranks of the world's most advanced wireless gaming mice with the release of G502 LIGHTSPEED. LIGHTSPEED is ultra-fast and reliable with performance trusted in competition by esports pros. G502 LIGHTSPEED also features the next-generation HERO 25K sensor and is POWERPLAY compatible. With this complete advanced technology remastering, G502 LIGHTSPEED still retains the same beloved shape - and achieves a 7-gram weight reduction.",
//     "specifications":[{
//                     "model":"910-005565",
//                     "Type":"Lightspeed Wireless",
//                     "Interface":"USB",
//                     "Tracking Method":"HERO 25K",
//                     "Maximum dpi":"25600 dpi",
//                     "Buttons":"11",
//                     "Mouse Adjustable Weight":"2 x 4g, 4 x 2g",
//                     "Scrolling Capability":"Tilt Wheel",
//                     "Color":"Black"}],
//     "img":"https://www.newegg.com/logitech-910-005565-g502-usb-lightspeed-wireless/p/N82E16826197336",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },{
//     "name":"Viper 8KHz",
//     "price":49.87,
//     "description":"Razer™ 8000Hz HyperPolling Technology: Sending up to 8 times more data in a second and reducing delay from 1 to 1/8th of a millisecond.",
//     "specifications":[{
//                     "model":"RZ01-03580100-R3U1",
//                     "Type":"Wired",
//                     "Interface":"USB",
//                     "Mouse Grip Style":"All",
//                     "Tracking Method":"Optical",
//                     "Maximum dpi":"20000 dpi",
//                     "Buttons":"8",
//                     "Color":"Black"}],
//     "img":"https://www.newegg.com/razer-rz01-03580100-r3u1-viper-8khz-usb-wired/p/32K-000N-00150",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"DeathAdder V2 Pro",
//     "price":69.99,
//     "description":"",
//     "specifications":[{
//                     "model":"RZ01-03350100-R3U1",
//                     "Type":"Bluetooth Wireless",
//                     "Interface":"Bluetooth",
//                     "Mouse Grip Style":"All",
//                     "Tracking Method ":"Optical",
//                     "Maximum dpi":"20000",
//                     "Hand Orientation":"Right Hand",
//                     "Color":"Black"}],
//     "img":"https://www.newegg.com/razer-rz01-03350100-r3u1-deathadder-v2-pro-bluetooth-wireless/p/32K-000N-00129",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"Clutch GM08",
//     "price":14.95,
//     "description":"12400 DPI",
//     "specifications":[{
//                     "model":"Storm",
//                     "Type":"Wired",
//                     "Interface":"USB",
//                     "Tracking Method":"Optical",
//                     "Color":"Black"}],
//     "img":"https://www.newegg.com/msi-s12-0401800-cla-clutch-gm08-usb-2-0-wired/p/N82E16826554042",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"X17",
//     "price":24.99,
//     "description":"Tripple Sensor 3-Dimension Array Tech.Quick Responding Mechanism.On the fly DPI Settings + 5 Onboard Profiles.Ergomic Design with Sniper Button.High Speed USB Max Polling/Report Rate: 8,000Hz.Customizable Weight System",
//     "specifications":[{
//                     "model":"903-W1-17BK-KR",
//                     "Type ":"Wired",
//                     "Interface":"USB",
//                     "Tracking Method":"Optical",
//                     "Maximum dpi ":"16000 dpi",
//                     "Buttons":"10",
//                     "Mouse Adjustable Weight":"Yes",
//                     "Color":"Black"}],
//     "img":"https://www.newegg.com/evga-903-w1-17bk-kr-x17-usb-wired/p/N82E16826188009",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"G27Q",
//     "price":239.99,
//     "description":"Safety FW update Black EqualizerAim Stabilizer Dashboard OSD Sidekick ameAssist PiP/PbP",
//     "specifications":[{
//                     "model":"G27Q",
//                     "Screen Size":"27",
//                     "Widescreen":"Yes",
//                     "Glare Screen":"Non-glare",
//                     "LED Backlight":"Yes",
//                     "Panel ":"IPS",
//                     "Display Type":"QHD",
//                     "Adaptive Sync Technology":"AMD FreeSync Premium",
//                     "Recommended Resolution":"2560 x 1440 (2K)",
//                     "Viewing Angle":"178° (H) / 178° (V)",
//                     "Aspect Ratio":"16:9",
//                     "Brightness":"350 cd/m2",
//                     "Contrast Ratio":"DCR 12,000,000:1 (1,000:1)",
//                     "Response Time":"1ms (MPRT)",
//                     "Pixel Pitch":"0.2331mm",
//                     "Refresh Rate":"144 Hz",
//                     "VESA Certified DisplayHDR":"DisplayHDR 400"}],
//     "img":"https://www.newegg.com/p/N82E16824012015",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"ED270 Xbmiipx",
//     "price":189.99,
//     "description":`Give yourself a competitive edge in eSports gaming with this ultra-fast 240 Hz refresh rate display. This 27" monitor also boasts a curved VA screen and Full HD resolution for an immersive, crystal-clear visual. Dual HDMI and one DisplayPort inputs play nice with the latest gaming desktops/laptops and game consoles. And a speaker is built in for added convenience. `,
//     "specifications":[{
//                     "model":"ED270 Xbmiipx",
//                     "Part Numbe":"UM.HE0AA.X01",
//                     "Cabinet Color":"Black",
//                     "Bezel Design":"3 Sided Frameless",
//                     "Screen Size":"27",
//                     "Widescreen":"Yes",
//                     "Glare Screen":"Anti-glare",
//                     "LED Backlight":"Yes",
//                     "Panel":"VA",
//                     "Display Type":"Full HD",
//                     "Adaptive Sync Technology":"FreeSync (AMD Adaptive Sync)",
//                     "Maximum Resolution":"1920 x 1080",
//                     "Viewing Angle":"178° (H) / 178° (V)",
//                     "Aspect Ratio":"16:9",
//                     "Brightness":"250 cd/m2",
//                     "Contrast Ratio":"ACM 100,000,000:1",
//                     "Response Time":"1ms (VRB)",
//                     "Display Colors":"16.7 Million",
//                     "Pixel Pitch":"0.3114mm",
//                     "Curvature Radius":"1500R"}],
//     "img":"https://www.newegg.com/black-acer-nitro-ed270-xbmiipx-um-he0aa-x01-27/p/N82E16824011367",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"TUF GAMING VG24VQ",
//     "price":179.99,
//     "description":"Trace Free Technology: Yes GamePlus (modes): Yes (Crosshair/Timer/FPS Counter/Display Alignment) Low Blue Light: YesHDCP support: YesGameVisual: 7 Modes (Scenery/Racing/Cinema/RTS/RPG/FPS/sRGB Modes/MOBA Mode)FreeSync technology supported Extreme Low Motion BlurGameFast Input technologyShadow Boost",
//     "specifications":[{
//                     "model":"VG24VQ",
//                     "Screen Size":`24" (Actual size 23.6")`,
//                     "Widescreen":"Yes",
//                     "LED Backlight":"Yes",
//                     "Panel":"VA",
//                     "Display Type":"Full HD",
//                     "Adaptive Sync Technology":"AMD FreeSync",
//                     "Recommended Resolution":"1920 x 1080",
//                     "Viewing Angle":"178° (H) / 178° (V)",
//                     "Aspect Ratio":"16:9",
//                     "Brightness":"350 cd/m2",
//                     "Contrast Ratio":"3000:1",
//                     "Response Time":"1ms MPRT",
//                     "Pixel Pitch":"0.272mm",
//                     "Refresh Rate":"144 Hz",
//                     "Curvature Radius":"1500R",
//                     "Curved Surface Screen":"Curved",
//                     "Horizontal Refresh Rate":"30 - 185 KHz",
//                     "Vertical Refresh Rate":"48 - 144 Hz"}],
//     "img":"https://www.newegg.com/black-asus-tuf-gaming-vg24vq-90lm0570-b011b0-23-6/p/N82E16824281027",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"Odyssey G32A LS32AG320NNXZA",
//     "price":329.99,
//     "description":"Eco Saving Plus Eye Saver ModeFlicker FreeGame ModeOff Timer PlusBlack Equalizer Refresh Rate Optimizor",
//     "specifications":[{
//                     "model":"LS32AG320NNXZA",
//                     "Screen Size":"32",
//                     "Widescreen":"Yes",
//                     "Panel":"VA",
//                     "Display Type":"Full HD",
//                     "Adaptive Sync Technology":"FreeSync Premium (AMD Adaptive Sync)",
//                     "Recommended Resolution":"1920 x 1080",
//                     "Viewing Angle":"178° (H) / 178° (V)",
//                     "Aspect Ratio":"16:9",
//                     "Brightness":"250 cd/m2 (Typical)",
//                     "Contrast Ratio":"3000:1 (Typical)",
//                     "Response Time":"1 ms (MPRT)",
//                     "Color Gamut":"72% NTSC",
//                     "Display Colors":"16.7 Million",
//                     "Refresh Rate":"165 Hz (Max)"}],
//     "img":"https://www.newegg.com/samsung-ls32ag320nnxza-32/p/N82E16824027109",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"X27qc",
//     "price":229.99,
//     "description":"Here comes silky-smooth high definition gaming. Lagging and stuttering will be a thing of the past with VA Panel Technology, 165Hz refresh rate, 1ms response time[1], and AMD[2] FreeSync Premium[3].",
//     "specifications":[{
//                     "model":"X27qc",
//                     "Screen Size":`27"`,
//                     "Widescreen":"Yes",
//                     "Glare Screen":"Anti-glare",
//                     "Panel":"VA",
//                     "Display Type":"QHD",
//                     "Adaptive Sync Technology":"FreeSync Premium (AMD Adaptive Sync)",
//                     "Recommended Resolution":"2560 x 1440 (2K)",
//                     "Viewing Angle":"178° (H) / 178° (V)"}],
//     "img":"https://www.newegg.com/hp-27-qhd/p/0JC-0019-02DZ4",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"UltraGear 24GN650-B",
//     "price":249.99,
//     "description":"The pinnacle of gaming monitors. Complete your battle station with a premium LG UltraGear Gaming Monitor. Built for gamers, it delivers the latest hardware, specs, ergonomics, sleek design and sensory experience. With gaming-focused features like 1ms GTG response times, pro-level customization and fast, vivid IPS panels, you're sure to gain an added edge.",
//     "specifications":[{
//                     "model":"24GN650-B",
//                     "Screen Size":`24"`,
//                     "Widescreen":"Yes",
//                     "Glare Screen":"Anti-glare",
//                     "LED Backlight":"Yes",
//                     "Panel":"IPS",
//                     "Adaptive Sync Technology":"FreeSync Premium (AMD Adaptive Sync)",
//                     "Maximum Resolution":"1920 x 1080",
//                     "Viewing Angle":"178° (H) / 178° (V)"}],
//     "img":"https://www.newegg.com/black-lg-ultragear-24gn650-b-24/p/N82E16824026176",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"Gaming Chair",
//     "price":159.99,
//     "description":"Racing style gaminng chair",
//     "specifications":[{
//                     "type":"Racing",
//                     "Primary Color":"Black",
//                     "Accent Color":"Black",
//                     "Material":"Faux Leather",
//                     "Frame Construction":"Manufactured Wood+steel",
//                     "Adjustable Degree":"90°-135°",
//                     "Armrests Included":"Yes",
//                     "Swivel":"Yes",
//                     "Wheels":"5",
//                     "Max Weight Supported":"250 lb."}],
//     "img":"https://www.newegg.com/p/358-005S-00037?Item=9SIAXKAE8J3033",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"Gaming Office Chair ",
//     "price":129.99,
//     "description":"Office chair",
//     "specifications":[{
//                     "model":"LS-669203",
//                     "Type":"Chair",
//                     "Primary Color":"Black / Red",
//                     "Material":"Mesh",
//                     "Frame Construction":"Metal"}],
//     "img":"https://www.newegg.com/black-red-dowinx-ls-669203-chair/p/358-007U-00028?Item=9SIAKUYGSA5499",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"Gaming Desk",
//     "price":84.99,
//     "description":"Inch Gaming Desk Racing Style PC Computer Desk Y-shaped Home Office with Desk Large Carbon Fiber Desktop, Cup Holder, Headphone Hook, Full Mouse Pad, and Gaming Handle Rack (Black)",
//     "specifications":[{
//                     "type":"Y-shape",
//                     "Surface Color":"Black",
//                     "Surface Material":"Carbon Fiber",
//                     "Surface Load Capacity":"170LBS",
//                     "Surface Width":"43.3 inch",
//                     "Surface Thickness":"0.6 inch"}],
//     "img":"https://www.newegg.com/p/1HJ-014B-00003?Item=9SIB9JKHAZ5333&cm_sp=SP-_-1053122-_-Pers_CategorySponsoredProduct-_-4-_-9SIB9JKHAZ5333-_-858-_--_-2",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"Gaming Chair",
//     "price":104.99,
//     "description":"This Homall Gaming Chair extends the full length of the back with support for the shoulders, head, and neck. Our chairs are crafted to perfection and designed to the bodies natural shape, you will find complete comfort with its quality PU leather.",
//     "specifications":[{
//                     "model":"T-OCRC0082",
//                     "Type":"Chair",
//                     "Primary Color":"Black",
//                     "Accent Color":"Black",
//                     "Material":"PU Leather",
//                     "Frame Construction":"Steel",
//                     "Adjustable Degree":"Tilt: 90 - 180 degree",
//                     "Swivel":"360 Degree",
//                     "Ergonomic":"Yes"}],
//     "img":"https://www.newegg.com/black-homall-t-ocrc0082-chair/p/358-003X-00001?Item=9SIB9J8H2Y4858&cm_sp=SP-_-1170229-_-Pers_CategorySponsoredProduct-_-4-_-9SIB9J8H2Y4858-_-858-_--_-1",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"GF Series GF63 Thin 11UC-270",
//     "price":679.99,
//     "description":"Heavyweight performance in a lightweight package. Powerful processor and graphics bring smooth, gorgeous visuals on the ultra fast 144 Hz IPS-level display. Play to the max with powerful yet quiet cooling and long battery life. And when it's time to hit the road, the GF63 Thin will never weigh you down.",
//     "specifications":[{
//                     "model":"GF63 Thin 11UC-270",
//                     "Operating System":"Windows 11 Home",
//                     "Color":"Black",
//                     "CPU":"Intel Core i5-11400H 2.70 GHz",
//                     "Screen":`15.6" 144 Hz IPS`,
//                     "Memory":"8 GB DDR4",
//                     "Storage":"256 GB NVMe SSD",
//                     "Graphics Card":"NVIDIA GeForce RTX 3050 Laptop GPU",
//                     "Video Memory":"4 GB GDDR6",
//                     "Communication":"Gigabit LAN and WLAN",
//                     "Dimensions (W x D x H)":`14.13" x 9.99" x 0.85"`,
//                     "Weight":"4.10 lbs."}],
//     "img":"https://www.newegg.com/black-msi-gf-series-gf63-thin-11uc-270-gaming/p/N82E16834156092",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"TUF Gaming F17",
//     "price":849.99,
//     "description":"Always ready for action, the TUF Gaming F17 excels at gaming, streaming, and everything in between with the Intel® Core™ CPU and GeForce RTX™ GPU. A superfast NVMe™ PCIe® SSD speeds up load times, while an open SSD slot makes it easy to add terabytes for more space.",
//     "specifications":[{
//                     "model":"FX706HCB-ES51",
//                     "Color":"Graphite Black",
//                     "Operating System":"Windows 11 Home 64-bit",
//                     "CPU":"Intel Core i5-11400H 2.70 GHz",
//                     "Screen":`17.3" 144 Hz IPS`,
//                     "Memory":"8 GB DDR4",
//                     "Storage":"512 GB M.2 NVMe PCIe 3.0 SSD",
//                     "Graphics Card":"NVIDIA GeForce RTX 3050 Laptop GPU Up to 1600MHz at 60W (75W with Dynamic Boost)",
//                     "Video Memory":"4 GB GDDR6",
//                     "Dimensions (W x D x H)":`15.71" x 10.59" x 0.92"-0.98"`,
//                     "Weight":"5.73 lbs",
//                     "CPU Type":"Intel Core i5 11th Gen",
//                     "CPU Speed":"11400H (2.70GHz)"}],
//     "img":"https://www.newegg.com/graphite-black-asus-tuf-gaming-f17-fx706hcb-es51/p/N82E16834236136",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"IdeaPad Gaming 3 15IHU6",
//     "price":609.99,
//     "description":"Stay on the top of leaderboard with the IdeaPad Gaming 3i, a truly eye-catching gaming PC that is power-packed with beast hardware and innovative thermal design. Immersive Nahimic surround sound audio and 15.6” FHD IPS display will make you totally lost in the game world.",
//     "specifications":[{
//                     "model":"82K1015DUS",
//                     "Color":"Shadow Black",
//                     "Operating System":"Windows 11 Home 64-bit",
//                     "CPU ":"Intel Core i5-11300H 3.10 GHz",
//                     "Screen":`15.6" 120 Hz IPS`,
//                     "Memory":"8 GB DDR4",
//                     "Storage":"512 GB M.2 2242 PCIe 3.0x4 NVMe SSD",
//                     "Graphics Card":"NVIDIA GeForce GTX 1650",
//                     "Video Memory":"4 GB GDDR6"}],
//     "img":"https://www.newegg.com/shadow-black-lenovo-ideapad-gaming-3-15ihu6-82k1015dus/p/N82E16834646427",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
// {
//     "name":"ROG Strix SCAR 15",
//     "price":1899.99,
//     "description":"Compete at the highest level of Windows 10 gaming with the ROG Strix SCAR 15. Take on any challenge with the powerful AMD Ryzen™ 9 5900HX CPU and GeForce RTX™ 3080 GPU. Input every strike with precision on a responsive optical mechanical keyboard. With a competitive edge this sharp, you can dominate any arena. ",
//     "specifications":[{
//                     "model":"G533QS-DS96",
//                     "Color":"Black",
//                     "Operating System":"Windows 10 Home 64-bit",
//                     "CPU ":"AMD Ryzen 9 5900HX 3.30 GHz",
//                     "Screen":`15.6" 300 Hz IPS`,
//                     "Memory":"16 GB DDR4",
//                     "Storage":"1TB M.2 NVMe PCIe 3.0 SSD",
//                     "Graphics Card":`NVIDIA GeForce RTX 3080 Laptop GPU
// With ROG Boost up to 1645MHz at 115W (130W with Dynamic Boost)`,
//                     "Video Memory ":"8 GB GDDR6"}],
//     "img":"https://www.newegg.com/black-asus-rog-strix-scar-15-g533qs-ds96-gaming-entertainment/p/N82E16834235896",
//     "stock":1,
//     "onDiscount":false,
//     "discountPercentage":0,
//     "freeShipping":false,
// },
//         {
//         "name": "ROG Strix SCAR 15",
//         "price": 1899.99,
//         "description": "Stay on the top of leaderboard with the IdeaPad Gaming 3i, a truly eye-catching gaming PC that is power-packed with beast hardware and innovative thermal design. Immersive Nahimic surround sound audio and 15.6” FHD IPS display will make you totally lost in the game world.",
//         "specifications": [{"color": "black", 
// 			   "operatingSystem": "Windows 10 Home 64-bit", 
// 			   "cpu": "AMD Ryzen 9 5900HX 3.30 GHz", 
// 			   "Screen": "15.6 300 Hz IPS", 
// 			   "memory": "16 GB DDR4",
// 			   "storage": "1 TB M.2 NVMe PCIe 3.0 SSD",
// 			   "graphicsCard": "NVIDIA GeForce RTX 3080 Laptop GPU-With ROG Boost up to 1645MHz at 115W (130W with Dynamic Boost)",
// 			   "videoMemory": "8 GB GDDR6",
// 			   "dimensions": "13.94 x 10.20 x 0.89-1.07",
// 			   "weight": "5.07 lbs"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/34-235-896-V01.jpg",
//         "stock": true,
//         "onDiscount": true,
//         "discountPercentage": 20,
//         "freeShipping": true
//     },
//     {
//         "name": "GE66 Raider 11UE-642",
//         "price": 1599.00,
//         "description": "GE66 Raider is equipped with the latest 11th Gen. Intel Core processors and powered by NVIDIA GeForce RTX 30 series graphics. Just as the spaceship traversing throughout the universe at warp speed with extreme performance, the GE66 landed at the gaming battlefield fully-armed. With the most comprehensive features, GE66 Raider will bring gamers to infinity and beyond.",
//         "specifications": [
// 			   {"model": "GE66 Raider 11UE-642",
// 			   "color": "Titanium Blue",
// 			   "operatingSystem": "Windows 11 Home", 
// 			   "cpu": "Intel Core i7-11800H 2.30 GHz", 
// 			   "Screen": "15.6 4K/UHD OLED", 
// 			   "memory": "16 GB DDR4",
// 			   "storage": "1 TB NVMe SSD",
// 			   "graphicsCard": "NVIDIA GeForce RTX 3060 Laptop GPU",
// 			   "videoMemory": "6 GB GDDR6",
// 			   "dimensions": "14.09 x 10.51 x 0.92",
// 			   "weight": "5.25 lbs"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/34-156-088-V28.jpg",
//         "stock": 523,
//         "onDiscount": true,
//         "discountPercentage": 11,
//         "freeShipping":true 
//     },
//     {
//         "name": "Legion 5 Pro",
//         "price": 1489.99,
//         "description": "",
//         "specifications": [
// 			   {"screenSize": "16.0",
// 			   "dateFirstAvailable": "December 21, 2021"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/A24GS220125QtAw6.jpg",
//         "stock": 394,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "Galaxy Book Odyssey",
//         "price": 1399.99,
//         "description": "A laptop PC that's packed with power for work or play. Crush all your productivity goals like never before, whether it's a work-related project or your personal to-do list. And when it's time to kick back, you can stream or game to your heart's content with stunning visuals and stellar audio, all powered by a long-lasting battery.",
//         "specifications": [
// 			   {"model": "NP762XDA-XA1US",
// 			   "color": "Mystic Black",
// 			   "operatingSystem": "Windows 11 Home 64-bit", 
// 			   "cpu": "Intel Core i7-11600H 2.90 GHz", 
// 			   "Screen": "15.6", 
// 			   "memory": "8 GB DDR4",
// 			   "storage": "512 GB SSD",
// 			   "graphicsCard": "NVIDIA GeForce RTX 3050 Ti Laptop GPU-NVIDIA Max-Q for peak performance and efficiency",
// 			   "videoMemory": "4 GB GDDR6",
// 			   "dimensions": "14.04 x 9.02 x 0.70",
// 			   "weight": "4.08 lbs",
// 			   "Other Features": "Fingerprint reader"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/34-132-455-V18.jpg",
//         "stock": 482,
//         "onDiscount": true,
//         "discountPercentage": 5,
//         "freeShipping": false
//     },
//     {
//         "name": "GameSir X2",
//         "price": 69.99,
//         "description": "In e-sports, we must race against time, because even the slightest delay can reverse the situation. Therefore, in order to create the most favorable situation for players, GameSir X2 uses a wired connection, which greatly reduces the time required for the device signal to reach the mobile phone, and truly realizes plug and play. With almost no delayed input, you can control the situation at any time without leaving the opponent's chances.",
//         "specifications": [
// 			   {"model": "GameSir X2",
// 			   "size": "177.8*84.3*36.8mm",
// 			   "androidBeam": "Android (Android 9.0 or later)",
// 			   "battery": "none",
// 			   "weight": "167g",
// 			   "dateFirstAvailable": "April 01, 2021"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/A9U6S220216i5xqM.jpg",
//         "stock": 365,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "GameSir G4pro",
//         "price": 49.99,
//         "description": "The chip of GameSir G4 Pro has been upgraded to be compatible with more platforms. Gamers can use GameSir G4 Pro on Apple iPhone,Android mobile phone,Windows PC and Nintendo Switch!",
//         "specifications": [
// 			   {"model": "GameSir G4pro",
// 			   "color": "Titanium Black",
// 			   "OS": "android Phone/Tablet/TV Box/iPhone/iPad/Apple TV/Windows PC",
// 			   "size": "4.21 x 6.14 x 2.52 inches",
// 			   "Wi-Fi": "2.4GHz Wireless",
// 			   "bluetooth": "bluetooth 4.2",
// 			   "USB": "Type-C",
// 			   "battery": "built-in 800mAh rechargeable Lithium battery",
// 			   "weight": "1.15 pounds",
// 			   "Date First Available": "April 08, 2021"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/A9U6S2106028V320.jpg",
//         "stock": 483,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "C8",
//         "price": 32.96,
//         "description": "1. Due to huawei's system reasons, huawei mobile phone does not support this product for the time being, RAM<2G, resolution 720P, mediatek 4 core and CPU kernel version MT65** start, etc. Some mediatek 4 cores can be used, such as zte xiaoxian 3 and gionee GN5001, and the CPU is 4-core MT6735. 2. 4G wireless bluetooth game controller, playing apple and android, mass games, intelligent chip, wireless connection, bluetooth 4.0, built-in lithium battery, comfortable handle, compatible with multiple systems. 3. Match bracket second - change game mobile phone, buy namely send handle bracket. 4. Compatibility with IOS & Andriod. 5. C8 Bluetooth gamepad 6. Support Android, iOS, Windows system 7. Intelligent power saving, long battery life 8. The material is made of ABS material, which has the characteristics of resistance to falling and environmental protection. 9. 3D rocker, 360 degree global high precision positioning, high sensitivity, meticulous control without pressure 10. Adopt one-point design to make the direction control more precise and flexible 11.",
//         "specifications": [
// 			   {"model": "C8",
// 			   "color": "Titanium Black",
// 			   "OS": "For Android / iOS / PC / PS3",
// 			   "size": "15*10.5*5.4cm",
// 			   "bluetooth": "4.0",
// 			   "battery": "500mAh",
// 			   "batteryLife": "10-15Hours",
// 			   "dateFirstAvailable": "July 30, 2019"},
// 			],
//         "img": "https://c1.neweggimages.com/ProductImage/AFJW_131798146317683383XmSI029ub5.jpg",
//         "stock": 461,
//         "onDiscount": true,
//         "discountPercentage": 15,
//         "freeShipping": false
//     },
//     {
//         "name": "Parlante JBL Charge 5 portátil con bluetooth teal 110V/220V",
//         "price": 144,
//         "description": "Bold JBL Original Pro Sound Take the amazing power of JBL Pro Sound with you. The JBL Charge 5 has an optimized long excursion driver, a separate tweeter, and dual JBL bass radiators, all delivering impressively rich and clear audio. Get that big room sound, even when outdoors. 20 hours of playtime The fun doesn’t have to stop. Packed with an incredible 20 hours of battery life, JBL Charge 5 lets you party all day and into the night. IP67 waterproof and dustproof To the pool. To the park.",
//         "specifications": [
// 			   {"color": "Teal",
// 			   "dateFirstAvailable": "January 12, 2022"},
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/A2GAS2201121EEUZ735.jpg",
//         "stock": 214,
//         "onDiscount": true,
//         "discountPercentage": 5,
//         "freeShipping": true
//     },
//     {
//         "name": "JBL GO 2 Portable Bluetooth Waterproof Speaker (Moss Green)",
//         "price": 76.99,
//         "description": "Featuring IPX7 water resistance and up to five hours of playtime, the JBL GO 2 is a stylish, compact speaker designed to be taken with you anywhere you go. Enjoy JBL-quality sound either by wirelessly streaming music from Bluetooth-compatible devices or by using an audio cable to connect to non-Bluetooth devices. With the built-in speakerphone, you can also have crystal-clear conference calls, hands free.",
//         "specifications": [
// 			   {"model": "JBLGO2GRNAM",
// 			   "color": "Moss Green",
// 			   "wirelessTechnology": "Bluetooth",
// 			   "totalPower": "Output power: 3.1W RMS",
// 			   "battery": "Lithium-ion polymer(3.7V, 730mAh)",
// 			   "playbackTime": "Battery charge time: 2.5 hours"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/2MA-003E-00174-S04.jpg",
//         "stock": 69,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "JBL GO3GRN GO 3 Portable Waterproof Speaker - Green",
//         "price": 49.95,
//         "description": "JBL Go 3 features bold styling and rich JBL Pro Sound. With its new eye-catching edgy design, colorful fabrics and expressive details this a must-have accessory for your next outing. Your tunes will lift you up with JBL Pro Sound, its IP67 waterproof and dustproof so you can keep listening rain or shine, and with its integrated loop, you can carry it anywhere. Go 3 comes in completely new shades and color combinations inspired by current street fashion. JBL Go 3 looks as vivid as it sounds.",
//         "specifications": [
// 			   {"type": "bluetoothAccessories",
// 			   "dateFirstAvailable": "December 21, 2021"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImage/A1CZD21122112FMUM24.jpg",
//         "stock": 321,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "Klipsch K-100SW 10-Inch Powered Subwoofer",
//         "price": 139.99,
//         "description": `Deep, thunderous bass is necessary to complete a powerful home theater system. The Klipsch K-100SW powered subwoofer incorporates a 10" front-firing driver and all-digital amplifier, capable of producing room-filling low frequency effects that can not only be heard but felt as well. Plus, it accepts line/LFE inputs, so you can hook it up to most receivers available on the market.`,
//         "specifications": [
// 			   {"model": "K100-SW",
// 			   "type": "Subwoofer",
// 			   "soldAs": "Sigle",
// 			   "driverUnits": "10 (25.4cm) poly-fiber front-firing woofer",
// 			   "powerRating": "Amplifier power: 100W / 250W",
// 			   "frequencyResponse": "32Hz-120Hz+/-3dB",
// 			   "connectors": "Line level / LFE RCA jacks"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/0S6-0033-001U0-03.jpg",
//         "stock": 332,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "LG CM4590 XBOOM 700W Bluetooth Music System",
//         "price": 212.90,
//         "description": "Searching for powerful sound? Look no further than this LG audio system which pumps out a commanding 700 watts of audio, more than enough to fill your room with booming tunes.",
//         "specifications": [
// 			   {"totalOutputPower": "700W Hi-Fi Shelf System",
// 			   "bluetoothRemoteApp": "yes",
// 			   "usbDirectRecording": "yes(3)",
// 			   "frontSpeakerSystem": "2 Way 2 Speaker",
// 			   "fmTuningRange": "87.5 - 108.0 MHz",
// 			   "powerConsumption": "80W",
// 			   "remoteControl": "Yes",
// 			   "shippingWeight": "37.7 lbs"},
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/V0MT_1_202001172072760476.jpg",
//         "stock": 573,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "M-Audio M-Track Solo 2-Channel USB Audio Interface",
//         "price": 78.40,
//         "description": "roduct Key Features, Mic/Line Input Mic/Preamp XLR, Suited For Home Recording,Interface Type USB Interface, Max. Number of Channels 2, Form Factor Portable,Features Phantom Power, Software Included",
//         "specifications": [
// 			   {"dateFirstAvailable": "March 22, 2021"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/APHCS210322gvDED.jpg",
//         "stock": 304,
//         "onDiscount": true,
//         "discountPercentage": 3,
//         "freeShipping": true
//     },
//     {
//         "name": "Focusrite Scarlett Solo 3rd Generation Audio Interface",
//         "price": 119.99,
//         "description": "The simplest model in the range, the third-generation Scarlett Solo provides singer-songwriters with a reassuringly easy recording process. Equipped with high performance 24-bit/192 kHz AD-DA converters, Scarlett guarantees the same professional sound quality throughout the third-generation range. Its features include a single upgraded third-generation",
//         "specifications": [
// 			   {"dateFirstAvailable": "December 06, 2019"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/12N-001B-00017-03.jpg",
//         "stock": 453,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "MOTU M2 Audio Interface",
//         "price": 199.95,
//         "description": "Equipped with the same ESS Sabre32 Ultra DAC Technology found in audio interfaces costing thousands, the M2 delivers an astonishing 120 dB Dynamic Range on its main outputs. ESS converters also drive the headphone output, which rivals dedicated headphone amplifiers costing hundreds. Ultra-clean preamp circuits produce a measured -129 dBu EIN on the mic inputs. Capture and monitor your audio with pristine clarity.",
//         "specifications": [
// 			   {"dateFirstAvailable": "April 17, 2020"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/A4P0D201222KCKER.jpg",
//         "stock": 343,
//         "onDiscount":false ,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "Hyperx QuadCast Microphone",
//         "price": 122.99,
//         "description": "Hyperx QuadCast Microphone, just good",
//         "specifications": [
// 			   {"model": "4P5P6AA",
// 			   "type": "Microphone",
// 			   "sensitivity ": "-36dB",
// 			   "bateFirstAvailable": "April 20, 2022"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/V009D2202090GBN8464.jpg",
//         "stock": 666,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "Blue Yeti Microphone (Blackout) with Boom Arm Stand, Pop Filter and Shock Mount",
//         "price": 300,
//         "description": "Blue Microphone’s incredibly popular series of Yeti Microphones are the premier option to help you with broadcast-quality podcasting, YouTube productions, Skype/VoIP and voice-over work, and video game streaming. The Yeti provides all the tools you need to broadcast your message with crystal clear clarity. Featuring 16-bit sound quality and plug 'n play operation for instant streaming with your PC or Mac, this microphone is ready to go whenever inspiration strikes.",
//         "specifications": [
// 			   {"bundleIncludes": "Blue Microphones Yeti Microphone",
// 			   "Date First Available": "July 03, 2019"},
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/0UK-000T-000E2-S05.jpg",
//         "stock": 342,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "Shure SM7B SM-7B Dynamic Broadcast Recording Microphone NEW",
//         "price": 386.17,
//         "description": "The Shure SM78 microphone is designed and built to capture smooth, warm vocals that connect the speaker to the listener. Both music and speech will sound clean and natural without off-axis audio, mechanical noise, breathiness, and hum from audio equipment. Perfect for broadcast, podcast, and recording in any professional studio where voices need to be handled with care.",
//         "specifications": [
// 			   {"model": "SM7B",
// 			   "type": "Dynamic Microphones"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/0UK-0006-00011-S05.jpg",
//         "stock": 263,
//         "onDiscount": true,
//         "discountPercentage": 15,
//         "freeShipping": false
//     },
//     {
//         "name": "Blue Yeti X Microphone - Black Out",
//         "price": 122.99,
//         "description": "No problems getting it up and running seconds on Windows 8 64-bit. No compatibility or quality issues what-so-ever. Compared this to the Blue Snowball and for the money having all of the different recording modes and the solid desktop stand sold me on the Yeti.",
//         "specifications": [
// 			   {"model": "988-000105",
// 			   "type": "Professional USB Microphone for Gaming, Streaming and Podcasting."}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImage/36-431-052-V01.jpg",
//         "stock": 163,
//         "onDiscount": true,
//         "discountPercentage": 20,
//         "freeShipping": false
//     },
//     {
//         "name": "Sennheiser HD 201 Over Ear Headphone Gaming Wired Headset 3.5mm Computer Earphones HD Microphone",
//         "price": 39.99,
//         "description": "Closed, dynamic hi-fi stereo headphones Rich, crisp bass response and faithful dynamic audio reproduction Good attenuation of ambient noise, HD microphone Lightweight construction designed specifically for long studio or DJ sessions Powerful bass, rhythm-driven music and increased signal levels for modern Extremely comfortable to wear due to ultra-lightweight design, even for all-day listening 1/8 plug ( 3.5 mm) with 1/4 ( 6.3 mm) adapter included",
//         "specifications": [
// 			   {"model": "HD201",
// 			   "type": "Noise Cancelling",
// 			   "color": "Black",
// 			   "connector": "3.5mm"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/AVT0S210411iGFmw.jpg",
//         "stock": 163,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "Sennheiser HD 400S Headphones",
//         "price": 65.91,
//         "description": "Sennheiser HD 400S headphones come with a sturdy folding design that's great to be taken anywhere you go. Powered by Sennheiser dynamic drivers, it delivers an outstanding audio experience with well-extended response and dynamic bass. The closed-back design blocks unwanted background noise to keep your listening experience truly private. Also, users will enjoy easy music control and hands-free calls with the built-in remote and microphone.",
//         "specifications": [
// 			   {"model": "HD 400S",
// 			   "type": "Over the Ear",
// 			   "color": "Black",
// 			   "frequencyResponse": "18Hz-20KHz",
// 			   "THD": "< 0.5 % (1 kHz, 100 dB SPL)",
// 			   "sensitivity": "120 dB SPL @ 1 kHz, 1V RMS",
// 			   "connector": "3.5mm",
// 			   "earCoupling": "Binaural"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/26-106-879-V01.jpg",
//         "stock": 263,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": false
//     },
//     {
//         "name": "Logitech - G PRO X WIRELESS 981-000906 DTS Headphone:X 2.0 Gaming Headset for Windows with Blue VO!CE Mic Filter Tech and LIGHTSPEED Wireless - Black",
//         "price": 165.80,
//         "description": "LIGHTSPEED wireless technology, only from Logitech G, lets you game wirelessly without compromises in latency, connectivity or battery. Play in complete freedom with 20+ hours battery life and a 13+ m range using robust 2.4 GHz frequency.",
//         "specifications": [
// 			   {"model": "981-000906",
// 			   "color": "Black",
// 			   "operatingTime": "20.0 hours",
// 			   "connectionType": "Wireless",
// 			   "Wireless Type": "RF"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll60/A86ED210416B5CNK.jpg",
//         "stock": 193,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     },
//     {
//         "name": "Microphone" ,
//         "price": 110,
//         "description": "",
//         "specifications": [
// 			   {"model": "988-000105",
// 			   "type": "Professional USB Microphone for Gaming, Streaming and Podcasting."}
// 			],
//         "img": "",
//         "stock": 163,
//         "onDiscount": true,
//         "discountPercentage": 20,
//         "freeShipping": false
//     },
//     {
//         "name": "Corsair VOID RGB ELITE Wireless Circumaural Premium Gaming Headset with 7.1 Surround Sound, White",
//         "price": 49.99,
//         "description": "Hear everything in 7.1 surround sound from the lightest footstep to the most thundering explosion thanks to premium, custom-tuned 50 mm high-density neodymium audio drivers with an expanded frequency range of 20 Hz - 30,000 Hz.",
//         "specifications": [
// 			   {"model": "VOID RGB ELITE Wireless",
// 			   "partNumber": "CA-9011202-NA/RF",
// 			   "color": "Whiter",
// 			   "operatingTime": "Up to 16 hours",
// 			   "connectionType": "Wireless",
// 			   "wirelessType": "RF",
// 			   "driverUnit": "Custom 50mm Neodymium"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/26-816-188-01.jpg",
//         "stock": 543,
//         "onDiscount": true,
//         "discountPercentage": 10,
//         "freeShipping": false
//     },
//     {
//         "name": "Corsair HS60 PRO SURROUND 3.5mm Connector Circumaural Gaming Headset, Carbon",
//         "price": 52.49,
//         "description": "High-quality, custom-tuned 50mm neodymium audio drivers deliver the range to hear everything you need to on the battlefield. Immerse yourself in 7.1 surround sound, creating a multi-channel audio experience that puts you right in the middle of your game.",
//         "specifications": [
// 			   {"model": "HS60 PRO SURROUND",
// 			   "partNumber": "CA-9011213-NA",
// 			   "color": "Carbon",
// 			   "connector": "3.5mm",
// 			   "connectionType": "Wired",
// 			   "wirelessType": "2.4 GHz ISM",
// 			   "driverUnit": "50mm"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImage/26-816-148-V09.jpg",
//         "stock": 363,
//         "onDiscount": true,
//         "discountPercentage": 5,
//         "freeShipping": true
//     },
//     {
//         "name": "Beyerdynamic DT 770 Pro 250 Ohm Studio Reference Closed-Back Headphones",
//         "price": 139.99,
//         "description": "For decades now, professional users all around the world have placed their trust in our classic range: DT 770/880/990 PRO. These benchmark-setting studio headphones, available in three different models, boast extremely detailed resolution and very transparent sound.",
//         "specifications": [
// 			   {"model": "DT 770 Pro 250 Ohm",
// 			   "partNumber": "459046",
// 			   "color": "Carbon",
// 			   "connector": "Over the Ear",
// 			   "type": "Wired",
// 			   "cordLength": "9.84 ft. coiled cable",
// 			   "weight": "0.60 lb"}
// 			],
//         "img": "https://c1.neweggimages.com/ProductImageCompressAll1280/ABMTD210323CUZFR.jpg",
//         "stock": 634,
//         "onDiscount": false,
//         "discountPercentage": 0,
//         "freeShipping": true
//     }
]



module.exports = {products}